/**
 * @file main.c
 * @author Benedikt Streicher (streicher.b@posteo.de)
 * @brief An example application for the Sensor Controller in the CC1352P1
 *
 * This application demonstrates how to use the Sensor Controller in the
 * CC1352P1. It is based on the Zephyr board specific example
 * cc13x2_cc26x2/system_off and extends it with the Sensor Controller.
 * It first runs through a sequence of busy-waiting, sleeping and standby and
 * then starts the Sensor Controller task. The Sensor Controller task waits for
 * a button press on the button 1. After the button press, the user has five
 * seconds to press button 2 at least five times. If at least presses are
 * detected, the Sensor Controller task will generate an alert event and wake up
 * the main CPU. The main CPU will then print the number of button presses and
 * shut down the system.
 *
 * @version 0.1
 * @date 2024-03-15
 * 
 * @copyright Copyright (c) 2019 Nordic Semiconductor ASA
 * @copyright Copyright (c) 2020 Linaro Ltd.
 * @copyright SPDX-License-Identifier: Apache-2.0
 * 
 */

#include <stdint.h>
#include <stdio.h>
#include <zephyr/kernel.h>
#include <zephyr/init.h>
#include <zephyr/device.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/sys/poweroff.h>

#include <driverlib/ioc.h>

#include "scif/scif.h"

#define BUSY_WAIT_S 1U
#define SLEEP_US 4000U
#define SLEEP_S     1U

extern void CC1352R1_LAUNCHXL_shutDownExtFlash(void);

/**
 * @brief Callback function for the Task control interface ready event
 *
 * This callback function is called whenever the Sensor Controller task control
 * interface completed a non-blocking task control operation.
 * It is not necessary to implement this callback function, but it can be used
 * to provide feedback to the user that the task control interface is ready. It
 * is also possible to use the callback to execute code only after the operation
 * has completed.
 */
void scCtrlReadyCallback(void) {
	printk("SCIF driver callback: Task control interface ready\n");
}

/**
 * @brief Callback function for the ALERT event from the Sensor Controller
 * 
 * This callback function is called from the Sensor Controller task after an
 * alert event is generated by it.
 * It handles the alert event by reading the count of button 2 presses from the
 * Sensor Controller task and printing it to the console.
 */
void scTaskAlertCallback(void) {
	// Clear the ALERT interrupt source
	scifClearAlertIntSource();

	uint8_t count;
	count = (uint8_t) scifTaskData.buttonTask.output.count;
	printk("Button press count: %u\n", count);

	// Clear the ALERT interrupt source
	scifClearAlertIntSource();

	// Shut the system down
	printk("Shutting down\n");
	sys_poweroff();
}

int main(void)
{
	printk("Initializing\n");

	/* Initialize the SCIF operating system abstraction layer */
	scifOsalInit();
	scifOsalRegisterCtrlReadyCallback(scCtrlReadyCallback);
	scifOsalRegisterTaskAlertCallback(scTaskAlertCallback);

	/* Initialize the SCIF driver */
	scifInit(&scifDriverSetup);

	/* Shut off external flash to save power */
	printk("Shutting down external flash\n\n");
	CC1352R1_LAUNCHXL_shutDownExtFlash();

	/* Busy-wait for 1s */
	printk("Busy-wait %u s\n", BUSY_WAIT_S);
	k_busy_wait(BUSY_WAIT_S * USEC_PER_SEC);

	/* IDLE for 4ms */
	printk("Sleep %u us (IDLE)\n", SLEEP_US);
	k_usleep(SLEEP_US);

	/* STANDBY for 1s */
	printk("Sleep %u s (STANDBY)\n\n", SLEEP_S);
	k_sleep(K_SECONDS(SLEEP_S));

	/* Start Sensor Controller task and go to sleep */
	printk("Starting Sensor Controller task and going to sleep\n");
	printk("Press button 1 to wake up and then button 2 at least 5 times.\n\n");
	scifStartTasksNbl(1 << SCIF_BUTTON_TASK_TASK_ID);
	k_sleep(K_FOREVER);
	
	CODE_UNREACHABLE;

	return 0;
}
